import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)
GPIO.setup(4, GPIO.OUT)
GPIO.setup(5, GPIO.OUT)
GPIO.setup(6, GPIO.OUT)

def makePattern(p1, t1, p2, t2, p3, t3, p4, t4, p5, t5, p6, t6):
	GPIO.output(p1, True)
	time.sleep(t1)
	GPIO.output(p1, False)
	GPIO.output(p2, True)
	time.sleep(t2)
	GPIO.output(p2, False)
	GPIO.output(p3, True)
	time.sleep(t3)
	GPIO.output(p3, False)
	GPIO.output(p4, True)
	time.sleep(t4)
	GPIO.output(p4, False)
	GPIO.output(p5, True)
	time.sleep(t5)
	GPIO.output(p5, False)
	GPIO.outuput(p6, True)
	time.sleep(t6)
	GPIO.output(p6, False)
	GPIO.cleanup()

print("LED 패턴 암기")
presskey = input()
print("Red = 4, Green = 5, Blue = 6\n")
print("키려는 색의 LED와 시간 순서로 총 6개 입력해주세요.")
color1 = int(input())
time1 = float(input())
color2 = int(input())
time2 = float(input())
color3 = int(input())
time3 = float(input())
color4 = int(input())
time4 = float(input())
color5 = int(input())
time5 = float(input())
color6 = int(input())
time6 = float(input())

makePattern(color1, time1, color2, time2, color3, time3, color4, time4, color5, time5, color6, time6)
